### ISSUE TITLE
Website Domain

### ISSUE THREAD

**Issue by Wurch** [actuarialopensource/website#6]
I've been looking for an available domain to our website. For now, these are most appropriate ones I could think of:
- actuarialosc.com
- actuarialopensource.[org|com|community]
- actuarialopensourcecommunity.com (maybe too long)

Do you have any more ideas or suggestions?

**Comment by fumitoh** [comment]
I think actuarialopensource.org is good.

**Comment by pdavidsonFIA** [comment]
openactuarial.org
opensourceactuaries.org

**Comment by fumitoh** [comment]
openactuarial.org is taken. openactuarial.net is available, which is now my best choice.

**Comment by pdavidsonFIA** [comment]
and what a page:
![image](https://user-images.githubusercontent.com/57438470/105728475-7c16c980-5f2c-11eb-8fed-ecdd49bb0c2d.png)

**Comment by fumitoh** [comment]
I googled it too!

**Comment by Wurch** [comment]
As suggested by @pdavidsonFIA, will be openactuarial.net then. I already prepared the server to resolve this domain to our still skeleton website, I hope in a few days push a working version. 

As a legitimate actuary, I'm having some visual design issues, front-end its hard stuff hahahaha
